// Generated by CoffeeScript 1.3.3

describe('Rotate', function() {
  return describe('#next()', function() {
    return describe('when initialized with [1, 2, 3]', function() {
      before(function() {
        return this.numbers = new Rotate([1, 2, 3]);
      });
      it('should return 1', function() {
        return expect(this.numbers.next()).to.equal(1);
      });
      it('should return 2', function() {
        return expect(this.numbers.next()).to.equal(2);
      });
      it('should return 3', function() {
        return expect(this.numbers.next()).to.equal(3);
      });
      return it('should return 1', function() {
        return expect(this.numbers.next()).to.equal(1);
      });
    });
  });
});
